#!/usr/bin/env node

//@ts-check
const perferedPort = 8002;

main();
async function main() {
	const express = require('express');
	const app = express();

	app.use(express.static(`${__dirname}`));
	app.get('/', (req, res) => res.redirect('/test/index.html'));
	app.use('/kill', (req, res) => {
		console.log(`/kill by http request`);
		process.nextTick(() => { res.end(`process.exit(0);`); process.exit(0); });
	});

	const port = await getPort();
	const url = `http://127.0.0.1:${port}/test/index.html`;

	app.listen(port);
	console.log(`test url: ${url}`);
	require('child_process').spawn('xdg-open', [url]);
}

function getPort() {
	return new Promise((resolve, reject) => {
		const server = require('net').createServer();
		server.unref();
		server.on('error', reject);
		server.listen({ port: perferedPort }, () => {
			const port = server.address().port;
			server.close(() => resolve(port));
		});
	});
}
